name: TIA Baseline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  baseline:
    uses: ./.github/workflows/tests.yml
    with:
      record-baseline: true
